name: Build TangoRestServer
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github-hzg
          server-username: GITHUB_USER
          server-password: GITHUB_TOKEN
      - name: Run maven
        env:
          GITHUB_USER: ${{ secrets.MAVEN_GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.MAVEN_GITHUB_TOKEN }}
        run: mvn -B package --file pom.xml
      - name: Build and Push docker
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: mvn dockerfile:build dockerfile:push -Ddockerfile.password=$DOCKER_HUB_TOKEN
